version: '3'
services:
#mssql docker
  rentanddrive-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - rentanddrive

  rentanddrive-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:RentAndDrive=Server=rentanddrive-sql,1433;Database=RentAndDriveDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - rentanddrive      
    links:
      - rentanddrive-sql
    depends_on:
      - rentanddrive-sql
      
networks:
  rentanddrive:
    driver: bridge